apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-job
spec:
  schedule: "* * * * *"   # Cron schedule (runs every 1 minute)
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 4
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: alpine-container
            image: alpine:latest
            command: ["sh", "-c", "echo Hello"]
          restartPolicy: OnFailure
