apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv-jegan # Replace 'jegan' with your name
  labels:
    name: jegan
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.127 # Replace this IP with your CentOS IP
    path: /mnt/nfs/jegan/mysql # Replace this path with /mnt/nfs/user1/mysql folder
