apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1

  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: mysql-external-storage
        persistentVolumeClaim:
          claimName: mysql-pvc-jegan 

      containers:
      - image: bitnami/mysql:latest
        name: mysql

        volumeMounts:
        - name: mysql-external-storage
          mountPath: /bitnami/mysql/data
        env:
        - name: PV_CLAIM_NAME
          valueFrom:
            configMapKeyRef:
              name: mysql-cm
              key: pvclaimname

        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
             secretKeyRef:
               name: mysql-login-credentials
               key: password 
