apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: app1-trigger
spec:
  broker: default
  filter:
    attributes:
      type: app1
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: firstapp
