apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: secondapp
spec:
  template:
    metadata:
      name: secondapp-v1
      annotation:
        autoscaling.knative.dev/target: "1"
    spec:
      containers:
      - image: quay.io/rhdevelopers/eventinghello:0.0.2
