apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: app2-trigger
spec:
  broker: default
  filter:
    attributes:
      type: app2
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: secondapp
