apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-backup-job
spec:
  completions: 1
  template:
    spec:
      containers:
        - name: postgres-backup-container
          image: bitnami/postgresql:latest
          command: ["pg_dump", "-U", "postgres", "postgres", "-f", "backup.sql"]
          env:
            - name: POSTGRESQL_PASSWORD 
              value: root@123 
          volumeMounts:
            - name: backup-volume
              mountPath: /bitnami/postgresql
      restartPolicy: Never 
      volumes:
        - name: backup-volume
          emptyDir: {}
