apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-backup-job
spec:
  completions: 1
  template:
    spec:
      containers:
        - name: postgres-backup-container
          image: ubuntu:22.04 
          command: ["tar", "cvfz","/backup/postgres-backup.tar.gz","--absolute-names","/bitnami/postgresql"]
          env:
            - name: POSTGRESQL_PASSWORD 
              value: root@123 
          volumeMounts:
            - name: pg-volume
              mountPath: /bitnami/postgresql

            - name: pgbackup-volume
              mountPath: /backup
      restartPolicy: Never 
      volumes:
        - name: pg-volume
          persistentVolumeClaim: 
          claimName: pg-pvc-jegan # Replace 'jegan' with your name

        - name: pgbackup-volume
          persistentVolumeClaim: 
          claimName: pgbackup-pvc-jegan # Replace 'jegan' with your name
