apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-jegan # Replace 'jegan' with your name
  labels:
    name: jegan # Replace 'jegan' with your name
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.127 # Replace this IP with Server1(10.10.15.32) or Server2(10.10.15.8) or Server3(10.10.15.27) dependending on your linux user 
    path: /mnt/nfs/jegan/redis1 # Replace this path with /mnt/nfs/user1/mysql folder

