apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: redis-pvc-jegan # Replace 'jegan' with your name
      containers:
      - name: redis
        image: bitnami/redis:latest

        volumeMounts:
        - name: redis-storage
          mountPath: /bitnami/redis/data

        env:
        - name: REDIS_PASSWORD
          value: root@123
