apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-v2
    ver: "2.0"
  name: hello-v2
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-v2
    ver: "2.0"
