apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: second-subscriber
spec:
  channel:
    apiVersion: messaging.knative.dev/v1
    kind: Channel
    name: hello-eventing-channel 
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: secondapp
