apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: my-ping-source
spec:
  schedule: "*/1 * * * *"
  data: '{"message": "Hello from Knative Ping Source"}'
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: hello
